### ISSUE TITLE
Non Compliance with DBUS naming conventions

### ISSUE THREAD

**Issue by vishwabmc** [openbmc/phosphor-state-manager#1]
These names are not adhering to the DBUS naming conventions as required by : https://dbus.freedesktop.org/doc/dbus-api-design.html

AS_IF([test "x$HOST_OBJPATH" == "x"], [HOST_OBJPATH="/xyz/openbmc_project/state/host"])
AS_IF([test "x$CHASSIS_OBJPATH" == "x"], [CHASSIS_OBJPATH="/xyz/openbmc_project/state/chassis"])
AS_IF([test "x$BMC_BUSNAME" == "x"], [BMC_BUSNAME="xyz.openbmc_project.State.BMC"])
AS_IF([test "x$BMC_OBJPATH" == "x"], [BMC_OBJPATH="/xyz/openbmc_project/state/BMC"])

**Comment by williamspatrick** [comment]
The only one that looks wrong based on our conventions is that BMC should be lowercase in this context (for the object path).

**Comment by geissonator** [comment]
The object path is now lower case bmc:
```
root@p10bmc:/lib/systemd/system# busctl tree xyz.openbmc_project.State.BMC
`-/xyz
  `-/xyz/openbmc_project
    `-/xyz/openbmc_project/state
      `-/xyz/openbmc_project/state/bmc0
```
