### ISSUE TITLE
POST to Chassis.Reset for invalid chassis ID returns 200 OK status code

### ISSUE THREAD

**Issue by FarahRasheed1** [openbmc/phosphor-state-manager#28]
## Problem ##

Sending a POST request to reset an invalid chassis that does not exist returns 200 OK. I reproduced this on QEMU.

It looks like the service is not validating the chassis ID correctly for `Chassis.Reset` action , leading it to respond with 200 OK even when the chassis doesn't exist.

### Curl command: ###

```
curl -v -k -u root:0penBmc -X POST https://localhost:2443/redfish/v1/Chassis/random_chassis_that_does_not_exist/Actions/Chassis.Reset \
-H "Content-Type: application/json" \
-d '{
    "ResetType": "PowerCycle"
}'
```

### Response: ###

```
{
  "@Message.ExtendedInfo": [
    {
      "@odata.type": "#Message.v1_1_1.Message",
      "Message": "The request completed successfully.",
      "MessageArgs": [],
      "MessageId": "Base.1.13.0.Success",
      "MessageSeverity": "OK",
      "Resolution": "None"
    }
  ]
}
```

### Logs ###

`Sep 17 14:48:32 romulus phosphor-chassis-state-manager[291]: Change to Chassis Requested Power State: xyz.openbmc_project.State.Chassis.Transition.PowerCycle`

**Comment by williamspatrick** [comment]
This looks like a bmcweb bug and not a PSM one?
